name: Integration tests

on:
  workflow_call:
    secrets:
      GHCR_TOKEN:
        required: true

jobs:
  integration-test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch Charm Under Test
        uses: actions/download-artifact@v4
        with:
          name: built-charm
          path: built/

      - name: Get Charm Under Test Path
        id: charm-path
        run: echo "charm_path=$(find built/ -name '*.charm' -type f -print)" >> $GITHUB_OUTPUT

      - name: Setup Canonical K8S
        run: |
          sudo snap install k8s --classic --channel=1.32-classic/stable
          cat << EOF | sudo k8s bootstrap --file -
          containerd-base-dir: /opt/containerd
          EOF
          sudo k8s enable network dns load-balancer local-storage
          sudo k8s set load-balancer.cidrs="10.0.0.2-10.0.0.10"
          sudo k8s status --wait-ready --timeout 5m

      - name: Enable Multus addon
        continue-on-error: true
        run: |
          sudo k8s kubectl apply -f https://raw.githubusercontent.com/k8snetworkplumbingwg/multus-cni/master/deployments/multus-daemonset-thick.yml
          sudo k8s kubectl -n kube-system rollout status daemonset/kube-multus-ds
          sudo k8s kubectl auth can-i create network-attachment-definitions

      - name: Setup operator environment
        run: |
          sudo snap install juju --channel=3.6/stable
          sudo k8s kubectl config view --raw | juju add-k8s test-cloud --client
          juju bootstrap --debug --verbose test-cloud --model-default test-mode=true

      - name: Run integration tests
        run: |
          export CHARM_PATH="../${{ steps.charm-path.outputs.charm_path }}"
          INTEGRATION=1 go test ./... -v -timeout 1200s
