name: Integration tests

on:
  workflow_call:
    secrets:
      GHCR_TOKEN:
        required: true

jobs:
  integration-test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch Charm Under Test
        uses: actions/download-artifact@v4
        with:
          name: built-charm
          path: built/

      - name: Get Charm Under Test Path
        id: charm-path
        run: echo "charm_path=$(find built/ -name '*.charm' -type f -print)" >> $GITHUB_OUTPUT

      - name: Install Canonical K8s
        run: |
          sudo systemctl stop containerd || true
          sudo rm -rf /run/containerd /var/lib/containerd /etc/containerd || true
          sudo snap install k8s --channel=1.32-classic/stable --classic
          sudo k8s bootstrap --timeout=5m
          sudo k8s status --wait-ready
          mkdir -p ~/.kube
          sudo k8s kubectl config view --flatten --raw  > ~/.kube/config

      - name: Install Multus CNI
        run: |
          kubectl apply -f https://raw.githubusercontent.com/k8snetworkplumbingwg/multus-cni/master/deployments/multus-daemonset-thick.yml

      - name: Install Juju
        run: |
          sudo snap install juju --channel=3/stable
          juju version

      - name: Run integration tests
        run: |
          INTEGRATION=1 go test ./... -v -timeout 1200s
