name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref == 'refs/heads/main' && format('ignore-main-{0}', github.run_id) || format('{0}-{1}', github.workflow, github.ref_name) }}
  cancel-in-progress: true

jobs:
  go-lint:
    uses: ./.github/workflows/go-lint.yaml
  
  go-vet:
    uses: ./.github/workflows/go-vet.yaml
  
  go-test:
    uses: ./.github/workflows/go-unittest.yaml

  build:
    needs:
      - go-lint
      - go-vet
      - go-test
    uses: ./.github/workflows/build.yaml
    secrets: inherit

  integration-test:
    # needs:
    #   - build
    uses: ./.github/workflows/integration-test.yaml
    secrets: inherit

  publish-charm:
    needs:
      - go-lint
      - go-vet
      - go-test
      - build
    if: ${{ github.ref_name == 'main' }}
    uses: ./.github/workflows/publish-charm.yaml
    secrets: inherit
